export default function Aboutus() {
    return (
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel eius libero 
           temporibus explicabo, debitis commodi alias id veniam ipsam, recusandae 
           distinctio molestias nesciunt repellendus quo dolor est voluptas. Provident, aliquam?
           Lorem, ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorem quaerat reprehenderit
            deleniti omnis quam praesentium quasi. Cum fugit exercitationem numquam nobis quibusdam ipsa
             optio delectus adipisci iusto repellat ducimus facilis eos, sint culpa modi esse ab est 
             temporibus aliquid nisi aperiam quae. Aliquid ipsa quod maiores expedita vero praesentium 
             quas dolore, iste magnam incidunt! Ad assumenda rerum explicabo commodi at nesciunt dolores 
             autem accusamus aliquid unde minus fugiat optio magnam nobis magni molestias, pariatur harum.
              Molestiae consequatur repudiandae neque maiores cum doloremque, hic possimus porro asperiores est vero illum accusamus molestias harum similique, ipsum autem at dolores dignissimos dolor optio. Fuga veritatis ipsa, sed provident sapiente saepe laudantium debitis culpa quo accusantium, 
           mollitia esse velit quos aperiam cum officiis? Laboriosam sapiente tempora asperiores minima, laudantium ratione amet hic ad nesciunt id officia exercitationem explicabo temporibus optio non, nemo libero quos magni. Maxime aperiam, exercitationem, quidem officiis itaque reprehenderit vitae numquam eos possimus ea eveniet accusantium architecto ab earum facilis repudiandae fuga quas placeat! Nihil incidunt, eius perferendis, reiciendis autem recusandae qui quam numquam sapiente corrupti esse, dolores temporibus assumenda aperiam quas porro minus aspernatur enim ducimus sint eligendi maxime. Consequatur aperiam impedit fugiat quisquam totam sequi, qui atque ad praesentium distinctio incidunt id eaque, excepturi fugit maxime saepe sapiente rerum delectus expedita exercitationem? Consequuntur ex, minus error necessitatibus quo amet porro eos alias. Possimus deserunt vel dolorum voluptate aperiam, eligendi exercitationem modi numquam rem optio sit adipisci excepturi commodi quidem. Ex, explicabo dolorem. Dolor earum, eaque qui voluptates perspiciatis pariatur harum hic quaerat perferendis atque soluta expedita veritatis porro beatae distinctio fuga quo blanditiis quas quisquam labore. Esse sit, vitae aspernatur, sequi deleniti animi ipsum cum exercitationem delectus velit iure dicta. Maxime error fuga esse repellat ea explicabo, aperiam cupiditate eius architecto reiciendis quis officia quo delectus placeat sequi cumque magnam! Quisquam ratione omnis nostrum nihil numquam repellendus id ex voluptatem tempore, dignissimos nisi praesentium nobis inventore, expedita, voluptates ducimus quaerat soluta blanditiis accusantium! Explicabo, delectus hic corporis nobis est ab necessitatibus iusto eveniet reiciendis recusandae alias, eligendi a dolor asperiores? Similique ex dicta iusto labore a, consectetur animi nemo, vel atque amet rem inventore corrupti doloribus iure in rerum commodi vitae quod dolorum non mollitia nihil suscipit ab nostrum! Nulla beatae aspernatur ratione id sunt nisi dolore? Libero, iure quo ratione at, veniam cum quod doloremque minus error quae neque ex hic soluta perspiciatis delectus itaque dolore repellendus voluptate temporibus modi ab reprehenderit, dignissimos aperiam. Iure corporis ea ratione veniam possimus, esse molestiae tempore eius iusto laboriosam asperiores facere officia quis impedit veritatis, sit aspernatur, quod modi pariatur natus! Sunt praesentium modi voluptatem molestias beatae deleniti, animi voluptate porro odit doloremque ipsa commodi, ex fugit hic laudantium. At aspernatur quaerat quis. Corporis velit, voluptatum quos adipisci odit inventore, possimus dignissimos eveniet totam unde ad fuga voluptatibus modi est consectetur? Ex harum facilis omnis, ut eveniet soluta aspernatur nulla blanditiis mollitia non nisi at nesciunt accusantium dignissimos maiores quod vel sunt, modi illum voluptatum magni corporis? Deserunt, quae odit?
        </p>
    )
}